all:
	gcc -c -Wall principal.c
	gcc -c -Wall aloca.c 
	gcc -c -Wall senoide.c
	gcc -c -Wall rms.c
	gcc -c -Wall exibir.c
	gcc principal.o aloca.o senoide.o rms.o exibir.o -o programa -lm
	./programa 90 30 10000 1 1


